version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "800:80"  

  mysql:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MySQL
      MYSQL_DATABASE: mydb  # Define a default database
      MYSQL_USER: user  # Create a non-root user
      MYSQL_PASSWORD: password  # Password for the non-root user

